Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Max: 1000
Style/Documentation:
  Include:
    - app/models/**/*
    - lib/**/*
Layout/LineLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Enabled: false
Documentation:
    Enabled: false
Metrics/PerceivedComplexity:
    Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 250